### ISSUE TITLE
Coder profile: Обновление информации с Github

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/iwentys#14]
1. Я, как пользователь с добавленным гитхабом, могу у себя в профиле запросить апдейт своих данных
2. Для обновления данный система запрашивает у гитхаба ряд данных:
   1. Данные профиля - имя, статус.
   2. Активность по дням
   3. Список открытых репозиториев
3. Полученные данные должны обновиться в системе

Нужно во всех местах где мы работает с данными с гитхаба переделать обращения так, чтобы мы тыкали базу. В базу нужно добавить всю нужную информацию + добавить метод для запуска обновления пока не сделана фоновая задача.

**Comment by hrrrrustic** [comment]
Либо я не понял, либо звучит крайне сомнительно. 
Я правильно понял, что пока Я не ткну это кнопку у себя, НИКТО не увидит мою реальную активность, которую Я просто не проапдейтил?

**Comment by InRedikaWB** [comment]
Нет, это не так. Данные будут высасывать как при создании, так и автоматически на фоне. Но вариант автоматического обновления на фоне каждые N минут еще в планах.
