### ISSUE TITLE
Guilds: Управление членами гильдии

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/iwentys#19]
1. Я, как пользователь с правами управления, открывая гильдию могу видеть список реквестов на вступление
2. Я могу принять реквест - он удаляется, а пользователь становится членом
3. Я могу отклонить реквест - реквест удаляется
4. Я могу удалить существующего пользователя из гильдии - он перестает быть ее членом, но может вступить обратно
5. Я могу заблокировать члена гильдии - он становится заблокированным и не может обратно вернуться
6. Я могу просматривать список заблокированных пользователей и убирать их оттуда

**Comment by hrrrrustic** [comment]
4. ...но может вернуться обратно.
Как в вк просто ткнуть "Вернуться" или заново кинуть заявку и дождаться одобрения?

**Comment by hrrrrustic** [comment]
"Как в вк" = 
![image](https://user-images.githubusercontent.com/35951936/88406450-612a9780-cdd9-11ea-9125-95c5352a6342.png)

**Comment by InRedikaWB** [comment]
Лучше сравнивать гильдии не с чатами, а с группами. Если группа открытая - можно ливать и возвращаться, но если она закрытая - после лива можно только заявку еще раз кинуть.
