### ISSUE TITLE
Guilds: Управление гильдией

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/iwentys#20]
Я, как куратор или создатель, могу:
1. Изменить название, информацию или логотип гильдии
2. Изменить тип членства
   1. При переходе из закрытой в открытую все реквесты ~удаляются~ принимаются.

**Comment by hrrrrustic** [comment]
Почему удаляются? В чем смысл? Почему не принять автоматически все?

**Comment by InRedikaWB** [comment]
Валидно. Изменю
