### ISSUE TITLE
Study leaderboard: Механизм получения рейтинга по предмету

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/iwentys#48]
1. Я, как пользователь, могу открыть [фильтр и] указать:
   1. Предмет
   2. Номер потока
   3. Номер потока + группу
   4. Семестр
2. Если я не указал предмет, то подразумевается, что я хочу получить сумму по всем
3. Если я не указал семестр, подразумевается, что я хочу получить текущий
4. Если я указал невалидное сочитание фильтров - должна бросаться ошибка
5. Для указаного предмета и потока я должен получить список студентов и их баллы
6. Список должен быть отсортирован по убыванию

**Comment by hrrrrustic** [comment]
могу открыть(что?) указать:
Номер потока + группу
В группе уже достаточно информации, нет?

**Comment by InRedikaWB** [comment]
@hrrrrustic Да, достаточно, но с точки зрения использования на UI, вполне вероятно что ты сначала будешь указывать поток, а потом у тебя появится выпадающий список групп и ты ее будешь указывать.
