### ISSUE TITLE
Achievements: Реализовать фоновый процесс обновления данных

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/iwentys#56]
Требуется реализовать механизм фоновой работы. Нужно запустить фоновый тред, добавить метод закидывания ему новых задач на выполнение:

1. Вместе со стартом системы запускается запускается фоновый поток
2. При каждой запросе этому потоку прилетает новый last request time
3. Если прошло больше N минут с момента последней активности этого пользователя - поток начинается выполняться
4. Цикл выполнения будет проверять для пользователя условия получения ачивок

Стоит учесть, что проверяться должны ачивки не только пользователя, но и гильдии, а также будут добавлены обновления баллов и статы на гитхабе

**Comment by hrrrrustic** [comment]
Ничо не понял. Но очень интересно
Серьезно, ноль представлений, что в итоге должен делать этот поток
