### ISSUE TITLE
Отображение строковых значений enum в Swagger

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/iwentys#74]
Нужно настроить свагер так, чтобы он для енамов писал их названием, а не число. Это позволить понимать что вернулось без проверки кода.

**Comment by hrrrrustic** [comment]
https://stackoverflow.com/questions/36452468/swagger-ui-web-api-documentation-present-enums-as-strings

**Comment by hrrrrustic** [comment]
ДА В СМЫСЛЕ
